TOKEN = "8893369285:AAHi1aRkGG8AJ5M66C_cNVGAmTOn_gvtM9M"

CHAT_ID = "-5191516408"

TIMEFRAME = "Min60"

PAIRS = [
    "BTC_USDT",
    "ETH_USDT",
    "SOL_USDT",
    "BNB_USDT",
    "TON_USDT",
    "ADA_USDT",
    "AAVE_USDT",
    "OP_USDT",
    "BCH_USDT",
    "ZEC_USDT",
    "NEAR_USDT",
    "ONDO_USDT",
    "WLD_USDT",
    "DASH_USDT"
]